const root = document.querySelector('#app');
const modalRoot = document.querySelector('#modal-root');
const toastEl = document.querySelector('#toast');
let token = localStorage.getItem('kms-fullstack-token') || '';
let currentUser = null;
let toastTimer;

const esc = (v = '') => String(v).replace(/[&<>'"]/g, c => ({ '&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;' }[c]));
const nl = value => esc(value).replace(/\n/g, '<br>');
const toast = text => { toastEl.textContent = text; toastEl.classList.add('show'); clearTimeout(toastTimer); toastTimer = setTimeout(() => toastEl.classList.remove('show'), 2400); };
const api = async (url, options = {}) => {
  const response = await fetch(url, { ...options, headers: { 'Content-Type':'application/json', ...(token ? { Authorization:`Bearer ${token}` } : {}), ...(options.headers || {}) } });
  const data = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(data.error || '请求失败。');
  return data;
};
const timeText = value => new Date(value).toLocaleDateString('zh-CN');
const typeName = type => ({ knowledge:'知识点', quick:'快速阅读', mcq:'选择题', formula:'数学公式', math:'数学题' }[type] || '知识点');
const typeOptions = selected => ['knowledge','quick','mcq','formula','math'].map(type => `<option value="${type}" ${type === selected ? 'selected' : ''}>${typeName(type)}</option>`).join('');
const closeModal = () => { modalRoot.innerHTML = ''; };
function modal(title, content) { modalRoot.innerHTML = `<div class="backdrop"><section class="modal" role="dialog" aria-modal="true"><button class="icon-close" data-close aria-label="关闭">×</button><h2>${esc(title)}</h2>${content}</section></div>`; modalRoot.querySelector('[data-close]').onclick = closeModal; }
function shell(content, active = 'home') {
  root.innerHTML = `<header class="topbar"><button class="brand" data-nav="home">知识管理系统 <span>全栈版</span></button><nav><button data-nav="home" class="${active === 'home' ? 'active' : ''}">复习本</button><button data-nav="profile" class="profile-button">${esc(currentUser?.avatar || '📚')} ${esc(currentUser?.nickname || '')}</button><button data-nav="logout">退出</button></nav></header><main class="page">${content}</main>`;
  root.querySelectorAll('[data-nav]').forEach(button => button.onclick = () => navigate(button.dataset.nav));
}
async function navigate(target) {
  if (target === 'logout') { await api('/api/auth/logout', { method:'POST' }).catch(() => {}); token = ''; currentUser = null; localStorage.removeItem('kms-fullstack-token'); return authView(); }
  if (target === 'profile') return profileModal();
  return dashboard();
}
function authView() {
  root.innerHTML = `<main class="auth-page"><section class="auth-card"><div class="auth-logo">📚</div><h1>知识管理系统</h1><p>本地全栈版 · 数据保存在本机 SQLite 数据库</p><div class="auth-tabs"><button class="active" data-mode="login">登录</button><button data-mode="register">注册</button></div><form id="auth-form"></form></section></main>`;
  const form = root.querySelector('#auth-form');
  const draw = mode => { root.querySelectorAll('[data-mode]').forEach(button => button.classList.toggle('active', button.dataset.mode === mode)); form.innerHTML = mode === 'login' ? `<label>账号<input name="username" required minlength="2" maxlength="30" autocomplete="username" /></label><label>密码<input name="password" type="password" required minlength="6" autocomplete="current-password" /></label><button class="primary wide">登录</button><p class="hint">首次使用请先注册账号。</p>` : `<label>账号<input name="username" required minlength="2" maxlength="30" autocomplete="username" /></label><label>昵称<input name="nickname" required maxlength="30" /></label><label>密码<input name="password" type="password" required minlength="6" autocomplete="new-password" /></label><button class="primary wide">创建本地账号</button><p class="hint">密码仅以哈希形式保存在本机。</p>`; form.onsubmit = async event => { event.preventDefault(); const value = Object.fromEntries(new FormData(form)); try { const result = await api(`/api/auth/${mode}`, { method:'POST', body:JSON.stringify(value) }); token = result.token; currentUser = result.user; localStorage.setItem('kms-fullstack-token', token); dashboard(); } catch (err) { toast(err.message); } }; };
  root.querySelectorAll('[data-mode]').forEach(button => button.onclick = () => draw(button.dataset.mode)); draw('login');
}
async function dashboard() {
  try {
    const data = await api('/api/dashboard');
    shell(`<section class="hero"><div><p class="eyebrow">本地学习空间</p><h1>你好，${esc(currentUser.nickname)}</h1><p>词汇、知识点、选择题和数学题都在一个复习系统中。</p></div><div class="hero-stats"><strong>${data.stats.total}</strong><span>总内容</span><strong>${data.stats.mcq}</strong><span>选择题</span><strong>${data.stats.math}</strong><span>数学内容</span></div></section><section class="section-head"><div><h2>我的复习本</h2><p>${data.books.length} 个复习本</p></div><button class="primary" id="new-book">＋ 新建复习本</button></section><section class="book-grid">${data.books.map(book => `<article class="book-card"><div><h3>${esc(book.name)}</h3><p>${esc(book.description || '未添加说明')}</p><span>${book.item_count} 条内容 · 创建于 ${timeText(book.created_at)}</span></div><div class="card-actions"><button class="primary" data-study="${book.id}">开始复习</button><button data-manage="${book.id}">管理</button></div></article>`).join('') || '<p class="empty">还没有复习本，请新建一个。</p>'}</section>`, 'home');
    root.querySelector('#new-book').onclick = newBookModal;
    root.querySelectorAll('[data-manage]').forEach(button => button.onclick = () => manageBook(button.dataset.manage));
    root.querySelectorAll('[data-study]').forEach(button => button.onclick = () => chooseRound(button.dataset.study));
  } catch (err) { if (/登录/.test(err.message)) { token = ''; localStorage.removeItem('kms-fullstack-token'); authView(); } else toast(err.message); }
}
function newBookModal() { modal('新建复习本', `<form id="book-form"><label>复习本名称<input name="name" maxlength="40" required autofocus placeholder="例如：高等数学" /></label><label>说明<textarea name="description" maxlength="100" placeholder="例如：极限、导数、积分"></textarea></label><div class="modal-actions"><button class="primary">创建</button><button type="button" data-close>取消</button></div></form>`); modalRoot.querySelector('[data-close]').onclick = closeModal; modalRoot.querySelector('#book-form').onsubmit = async event => { event.preventDefault(); try { await api('/api/notebooks', { method:'POST', body:JSON.stringify(Object.fromEntries(new FormData(event.target))) }); closeModal(); dashboard(); } catch (err) { toast(err.message); } }; }
function profileModal() { modal('个人资料', `<form id="profile-form"><div class="avatar-picker"><button type="button" data-avatar="📚">📚</button><button type="button" data-avatar="🧠">🧠</button><button type="button" data-avatar="✏️">✏️</button><button type="button" data-avatar="🧮">🧮</button><button type="button" data-avatar="🌟">🌟</button></div><label>昵称<input name="nickname" required maxlength="30" value="${esc(currentUser.nickname)}" /></label><label>头像（可输入 emoji 或图片网址）<input name="avatar" maxlength="300" value="${esc(currentUser.avatar)}" /></label><div class="modal-actions"><button class="primary">保存资料</button><button type="button" data-close>取消</button></div></form>`); const form = modalRoot.querySelector('#profile-form'); modalRoot.querySelector('[data-close]').onclick = closeModal; modalRoot.querySelectorAll('[data-avatar]').forEach(button => button.onclick = () => { form.avatar.value = button.dataset.avatar; }); form.onsubmit = async event => { event.preventDefault(); try { currentUser = (await api('/api/profile', { method:'PUT', body:JSON.stringify(Object.fromEntries(new FormData(form))) })).user; closeModal(); dashboard(); } catch (err) { toast(err.message); } }; }
async function manageBook(bookId) {
  try {
    const data = await api(`/api/notebooks/${bookId}/items?sort=desc`); const book = data.book;
    shell(`<section class="manage-head"><div><button class="back" data-nav="home">← 返回</button><h1>${esc(book.name)}</h1><p>${esc(book.description || '管理内容、练习与导入')}</p></div><div class="manage-buttons"><button class="primary" id="study-book">开始复习</button><button id="add-item">添加内容</button><button id="bulk-import">批量导入</button><button class="danger" id="delete-book">删除复习本</button></div></section><section class="filterbar"><input id="search" placeholder="搜索题干、答案或标签" /><button id="search-btn">搜索</button><button id="sort-btn">最新在前</button></section><section class="item-list">${data.items.map((item,index) => itemCard(item, index + 1)).join('') || '<p class="empty">这里还没有内容。可添加单条内容或批量导入。</p>'}</section>`, 'home');
    root.querySelector('#study-book').onclick = () => chooseRound(bookId); root.querySelector('#add-item').onclick = () => itemModal(bookId); root.querySelector('#bulk-import').onclick = () => bulkModal(bookId); root.querySelector('#delete-book').onclick = async () => { if (confirm(`确定删除“${book.name}”及全部内容吗？`)) { await api(`/api/notebooks/${bookId}`, { method:'DELETE' }); dashboard(); } };
    root.querySelector('#search-btn').onclick = () => loadFiltered(bookId, root.querySelector('#search').value, 'desc'); root.querySelector('#sort-btn').onclick = () => loadFiltered(bookId, root.querySelector('#search').value, 'asc'); root.querySelectorAll('[data-edit]').forEach(button => button.onclick = () => itemModal(bookId, data.items.find(item => item.id === Number(button.dataset.edit)))); root.querySelectorAll('[data-delete]').forEach(button => button.onclick = async () => { if (confirm('确定删除这条内容吗？')) { await api(`/api/items/${button.dataset.delete}`, { method:'DELETE' }); manageBook(bookId); } });
  } catch (err) { toast(err.message); }
}
async function loadFiltered(bookId, query, sort) { const data = await api(`/api/notebooks/${bookId}/items?sort=${sort}&q=${encodeURIComponent(query)}`); const list = root.querySelector('.item-list'); list.innerHTML = data.items.map((item,index) => itemCard(item, index + 1)).join('') || '<p class="empty">没有匹配的内容。</p>'; root.querySelectorAll('[data-edit]').forEach(button => button.onclick = () => itemModal(bookId, data.items.find(item => item.id === Number(button.dataset.edit)))); root.querySelectorAll('[data-delete]').forEach(button => button.onclick = async () => { if (confirm('确定删除这条内容吗？')) { await api(`/api/items/${button.dataset.delete}`, { method:'DELETE' }); manageBook(bookId); } }); }
function itemCard(item, number) { const body = item.type === 'mcq' ? `<ol class="options">${item.options.map(option => `<li>${esc(option)}</li>`).join('')}</ol>` : ''; const formula = item.formula ? `<pre class="formula">${esc(item.formula)}</pre>` : ''; return `<article class="item-card"><div class="item-number">${number}</div><div class="item-main"><div class="badges"><span>${typeName(item.type)}</span><span>难度 ${'●'.repeat(item.difficulty)}</span>${item.tags ? `<span>${esc(item.tags)}</span>` : ''}</div><h3>${nl(item.prompt)}</h3>${formula}${body}${item.answer ? `<p class="item-answer">答案：${nl(item.answer)}</p>` : ''}</div><div class="item-actions"><button data-edit="${item.id}">编辑</button><button class="danger" data-delete="${item.id}">删除</button></div></article>`; }
function itemModal(bookId, item = null) { const value = item || { type:'knowledge', prompt:'', answer:'', formula:'', options:[], tags:'', difficulty:2 }; modal(item ? '编辑内容' : '添加内容', `<form id="item-form"><label>类型<select name="type">${typeOptions(value.type)}</select></label><label>题干 / 知识点<textarea name="prompt" required placeholder="输入词汇、知识点、题目或题干">${esc(value.prompt)}</textarea></label><label>答案 / 解析<textarea name="answer" placeholder="词汇中文、知识点解释、选择题正确选项或解析">${esc(value.answer)}</textarea></label><label>选择题选项（每行一个，可选）<textarea name="options" placeholder="A. 选项一\nB. 选项二">${esc((value.options || []).join('\n'))}</textarea></label><label>LaTex 数学公式（可选）<textarea name="formula" placeholder="例如：\\lim_{x \\to 0} \\frac{\\sin x}{x} = 1">${esc(value.formula)}</textarea></label><div class="two-fields"><label>标签<input name="tags" value="${esc(value.tags)}" placeholder="如：极限、英语" /></label><label>难度<select name="difficulty">${[1,2,3,4,5].map(n => `<option ${n === Number(value.difficulty) ? 'selected' : ''} value="${n}">${n}</option>`).join('')}</select></label></div><p class="hint">英文快速阅读未填答案时，会从本地词典自动查找中文。</p><div class="modal-actions"><button class="primary">保存</button><button type="button" data-close>取消</button></div></form>`); const form = modalRoot.querySelector('#item-form'); modalRoot.querySelector('[data-close]').onclick = closeModal; form.onsubmit = async event => { event.preventDefault(); const body = Object.fromEntries(new FormData(form)); body.options = body.options.split(/\r?\n/).map(v => v.trim()).filter(Boolean); if (body.type === 'quick' && !body.answer.trim() && window.OFFLINE_DICTIONARY) body.answer = window.OFFLINE_DICTIONARY[body.prompt.trim().toLowerCase()] || ''; if (body.type === 'quick' && !body.answer.trim()) return toast('本地词典未收录该词汇或短语，请手动填写答案。'); try { await api(item ? `/api/items/${item.id}` : `/api/notebooks/${bookId}/items`, { method:item ? 'PUT' : 'POST', body:JSON.stringify(body) }); closeModal(); manageBook(bookId); } catch (err) { toast(err.message); } }; }
function bulkModal(bookId) { modal('批量导入题库', `<div class="import-tabs"><button data-mode="knowledge" class="active">知识点</button><button data-mode="quick">词汇/阅读</button><button data-mode="mcq">选择题</button><button data-mode="formula">公式</button><button data-mode="math">数学题</button></div><p id="bulk-help" class="hint"></p><form id="bulk-form"><textarea name="bulk" required autofocus></textarea><div class="modal-actions"><button class="primary">导入</button><button type="button" data-close>取消</button></div></form>`); const help = modalRoot.querySelector('#bulk-help'); const form = modalRoot.querySelector('#bulk-form'); let mode = 'knowledge'; const examples = { knowledge:'每行一条，整行作为纯知识点保存。', quick:'每行一条：英文 ||| 中文。只写英文时会由本地词典补中文。', mcq:'每行一题：题干 ||| 选项A;选项B;选项C;选项D ||| 正确答案/解析。', formula:'每行一条：名称 ||| LaTex公式 ||| 说明。', math:'每行一题：数学题 ||| 答案或解析 ||| 可选公式。' }; const draw = () => { help.textContent = examples[mode]; form.bulk.placeholder = mode === 'mcq' ? '函数 y=x² 的顶点是？ ||| A.(0,0);B.(1,1);C.(-1,1);D.(0,1) ||| A' : mode === 'formula' ? '极限公式 ||| \\lim_{x \\to 0} \\frac{\\sin x}{x}=1 ||| 常用极限' : '内容一\n内容二'; modalRoot.querySelectorAll('[data-mode]').forEach(button => button.classList.toggle('active', button.dataset.mode === mode)); }; modalRoot.querySelectorAll('[data-mode]').forEach(button => button.onclick = () => { mode = button.dataset.mode; draw(); }); modalRoot.querySelector('[data-close]').onclick = closeModal; draw(); form.onsubmit = async event => { event.preventDefault(); const lines = form.bulk.value.split(/\r?\n/).map(line => line.trim()).filter(Boolean); const entries = lines.map(line => { const parts = line.split(/\s*\|\|\|\s*/); if (mode === 'knowledge') return { type:mode, prompt:line }; if (mode === 'quick') return { type:mode, prompt:parts[0], answer:parts.slice(1).join('|||') || (window.OFFLINE_DICTIONARY?.[parts[0].trim().toLowerCase()] || '') }; if (mode === 'mcq') return { type:mode, prompt:parts[0], options:(parts[1] || '').split(';').map(v => v.trim()).filter(Boolean), answer:parts.slice(2).join('|||') }; if (mode === 'formula') return { type:mode, prompt:parts[0], formula:parts[1] || '', answer:parts.slice(2).join('|||') }; return { type:mode, prompt:parts[0], answer:parts[1] || '', formula:parts.slice(2).join('|||') }; }); try { const result = await api(`/api/notebooks/${bookId}/bulk`, { method:'POST', body:JSON.stringify({ mode, entries }) }); closeModal(); toast(`已导入 ${result.added} 条${result.duplicate.length ? `，跳过 ${result.duplicate.length} 条重复` : ''}。`); manageBook(bookId); } catch (err) { toast(err.message); } }; }
function chooseRound(bookId) { modal('开始一轮复习', `<form id="round-form"><label>本轮数量<input name="count" type="number" min="1" max="200" value="20" required /></label><p class="hint">系统将从该复习本随机抽取内容。选择题可直接作答；其他内容点击显示答案。</p><div class="modal-actions"><button class="primary">开始</button><button type="button" data-close>取消</button></div></form>`); modalRoot.querySelector('[data-close]').onclick = closeModal; modalRoot.querySelector('#round-form').onsubmit = async event => { event.preventDefault(); try { const round = await api(`/api/notebooks/${bookId}/study`, { method:'POST', body:JSON.stringify(Object.fromEntries(new FormData(event.target))) }); closeModal(); studyView(bookId, round); } catch (err) { toast(err.message); } }; }
function studyView(bookId, round) { if (!round.items.length) return toast('该复习本还没有内容。'); let position = 0; let revealed = false; const render = () => { const item = round.items[position]; const mcq = item.type === 'mcq'; shell(`<section class="study-top"><button class="back" data-nav="home">← 结束复习</button><span>${esc(round.book.name)} · ${position + 1} / ${round.items.length}</span></section><section class="study-card"><span class="study-type">${typeName(item.type)}</span><div class="study-prompt">${nl(item.prompt)}</div>${item.formula ? `<pre class="formula study-formula">${esc(item.formula)}</pre>` : ''}${mcq ? `<div class="study-options">${item.options.map((option,index) => `<button data-choice="${index}">${esc(option)}</button>`).join('')}</div>` : ''}</section><section class="answer-card ${revealed ? 'shown' : ''}">${revealed ? `<p>${nl(item.answer || '无额外答案')}</p>` : '<p>点击右侧“查看答案”后显示答案或解析。</p>'}</section><section class="study-controls"><button id="prev" ${position === 0 ? 'disabled' : ''}>← 上一条</button><button id="mark-wrong">重点复习</button><button class="primary" id="next">${revealed || !item.answer ? '下一条 →' : '查看答案 →'}</button></section>`, 'home'); root.querySelector('#prev').onclick = () => { position -= 1; revealed = false; render(); }; root.querySelector('#next').onclick = async () => { if (!revealed && item.answer) { revealed = true; render(); return; } await api(`/api/items/${item.id}/review`, { method:'POST', body:JSON.stringify({ correct:true }) }).catch(() => {}); position = (position + 1) % round.items.length; revealed = false; render(); }; root.querySelector('#mark-wrong').onclick = async () => { await api(`/api/items/${item.id}/review`, { method:'POST', body:JSON.stringify({ correct:false }) }).catch(() => {}); toast('已记录为重点复习内容。'); }; root.querySelectorAll('[data-choice]').forEach(button => button.onclick = () => { revealed = true; render(); }); }; render(); }
(async () => { if (!token) return authView(); try { currentUser = (await api('/api/auth/me')).user; dashboard(); } catch { token = ''; localStorage.removeItem('kms-fullstack-token'); authView(); } })();
